# WireframeEditorWeb UI - production configuration

import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :koalemos, WireframeEditorWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"
